from django.urls import path
from . import views

urlpatterns = [
    path('admin/', views.demo, name='admin'),
    path('', views.home, name='home'),
    path('features/', views.features, name='features'),
    path('demo/', views.demo, name='demo'),
    path('works/', views.works, name='works'),
    path('support/', views.support, name='support'),
    path('home1', views.home1, name='home1'),
    path('profile/', views.profile, name='profile'),
    path('profile/edit/<str:student_id>/', views.edit_profile, name='edit_profile'),
    path('fees/', views.fees, name='fees'),
    path('homework/', views.homework, name='homework'),
    path('time/', views.time, name='time'),
    path('attendance/', views.attendance, name='attendance'),
    path('register/', views.register, name='register'),
    path('login/', views.student_login, name='login'),
    path('password-reset/', views.password_reset, name='password_reset'),
    path('change-password/', views.change_password, name='change_password'),
    path('base/', views.base, name='base'),
    path('notices/', views.notices, name='notices'),
    path('exam/', views.exam, name='exam'),
    path('results/', views.results, name='results'),
    path('subject/', views.subject, name='subject'),
    path('teacher/', views.teacher, name='teacher'),
    path('bus/', views.bus, name='bus'),
    path('hostel/', views.hostel_list, name='hostel'),
    path('library/', views.library, name='library'),
    path('logout/', views.logout, name='logout'),
    path('seating/', views.seating, name='seating'),
    path('about/', views.about, name='about'),
    path("activities/", views.activities_page, name="activities"),
    path("certificates/", views.certificates_page, name="certificates"),
    path('student/<str:student_id>/documents/', views.student_documents, name='student_documents'),
    path('student/<str:student_id>/documents/add/', views.add_document, name='add_document'),
    path('documents/<int:doc_id>/update/', views.update_document, name='update_document'),
    path('documents/<int:doc_id>/delete/', views.delete_document, name='delete_document'),
    path('timeline/', views.timeline, name='timeline'),
    path('timeline/delete/<int:status_id>/', views.delete_timeline, name='delete_timeline'),
    path("search-result/", views.search_result, name="search_result"),
    path('downloads/', views.downloads, name='downloads'),
    path('file/<int:pk>/', views.download_file, name='file'),
    path('delete/<int:pk>/', views.delete_file, name='delete'),

]