# Generated by Django 5.2 on 2025-09-01 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OLSS', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timelineimage',
            name='timeline',
        ),
        migrations.DeleteModel(
            name='Timeline',
        ),
        migrations.DeleteModel(
            name='TimelineImage',
        ),
    ]
