# Generated by Django 5.2 on 2025-09-07 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OLSS', '0002_downloadfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadfile',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='OLSS.student'),
        ),
    ]
