# Generated by Django 5.2 on 2025-09-07 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OLSS', '0003_downloadfile_uploaded_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, default='img_5.png', null=True, upload_to='profile_photos/'),
        ),
    ]
