# Generated by Django 5.2 on 2025-09-02 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OLSS', '0003_timeline_timelinefile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timelinefile',
            name='timeline',
        ),
        migrations.DeleteModel(
            name='Timeline',
        ),
        migrations.DeleteModel(
            name='TimelineFile',
        ),
    ]
