# Generated by Django 5.2 on 2025-09-07 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OLSS', '0004_alter_student_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, default='profile_photos/img_5.png', null=True, upload_to='profile_photos/'),
        ),
    ]
