# Generated by Django 5.2 on 2025-09-07 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OLSS', '0005_alter_student_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
    ]
