# Generated by Django 5.2 on 2025-09-15 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OLSS', '0009_query'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('category', models.CharField(choices=[('Vacation', 'Vacation'), ('Activity', 'Activity')], max_length=20)),
                ('description', models.TextField()),
            ],
        ),
    ]
